### ISSUE TITLE
Media player spawns lot of threads and sometimes crashes.

### ISSUE THREAD

**Issue by bredov** [Nibby/WeiqiTool#1]
It appears `MediaPlayer` constructor isn't thread-safe (internally it iterates over a shared list without synchronization) which may lead to a `ConcurrentModificationException` in certain circumstances which are hard to reproduce and couple times i've even encountered `NullPointerException` which completely killed any sound playback.

It seems there is no need to create `MediaPlayer` in a new `Thread` as internally `MediaPlayer` is non-blocking and spawns more threads to do playback. Which has its own drawback as it doesn't dispose those threads by its own in any reasonable time, that leads to thousands of running threads after some time of using the program, spawned only to do sounds.

I suggest to get rid of `Thread` spawning, or at least use `Platform.runLater` instead (though it doesn't seem to be neccessary). Also, to address massive thread spawn which `MediaPlayer` performs, the call to dispose method should be emitted. In my tests call to dispose() showed a performace degradation and sound chuckling when stones are placed very fast, so it may be reasonable to run that in it's own thread. As it is a minor task, a `ThreadPoolExecutor` with `Executors.newCachedThreadPool()` may be used to perform it. Making it so, I haven't encountered more race conditions, though more testing/investigation is needed to be sure. But at least dispose method performs synchronization, so it should be safe to call from another thread.

The code may look as follows
```java
private static ThreadPoolExecutor pool = (ThreadPoolExecutor) Executors.newCachedThreadPool();

public static void playSound(Media media) {
    if (media == null)
        return;

    MediaPlayer player = new MediaPlayer(media);
    player.play();
    player.setOnEndOfMedia(() -> pool.execute(player::dispose));
}
```

**Comment by Nibby** [comment]
Running the project in the IDE doesn't seem to have audio issues but it isn't until I create the app bundle does it resurface. Thank you for investigating the issue.

Thread spawning was a hack used another sound playback service, I should've read up on MediaPlayer before jolting it down. After briefly reading over the MediaPlayer docs it does seem it's rather inadequate. 

The solution you provided looks promising, though on Mac OS X 10.11 (JDK 8 u122) the program fails to exit and must be force quit each time. Reverting back to the traditional Java sound clip player may be an alternative approach.

**Comment by Nibby** [comment]
The latest commit that uses the AudioClip approach from javax.swing has proven to fix this issue.

**Comment by bredov** [comment]
Thanks for looking into, crashes did disappear, but problem with excessive thread spawning still persists. It seems it is required to call `close` method on `Clip` object to release underlying resources used to play an audio. It may be called when `STOP` event occurres, like so:
```java
// ...
clip.start();
clip.addLineListener((event) -> {
    if (event.getType() == LineEvent.Type.STOP) {
        clip.close();
    }
});
```

As for program fails to exit with solution i've suggested, it is because of thread pool. JavaFx won't exit program while non-daemon threads are active. So either the thread pool must be explicitly shutdown using `shutdown` method (for example in `stop` method override of class `Main`) or by providing a thread factory to `newCachedThreadPool` which will explicitly set a thread as a daemon. Of course, the simplest way is reverting back to your solution as to spawn new thread each time.

Also, AudioClip commit introduced a bug for me, when trying to run built JAR artifact on Windows: sound doesn't play because of an exception `java.io.IOException: mark/reset not supported`. Quick google revealed that `AudioSystem.getAudioInputStream` requires seek operation support on a stream and it seems it isn't supported on a compressed file (which jar is). I've managed to resolve issue by switching to this code:
```java
AudioInputStream input = AudioSystem.getAudioInputStream(Resources.class.getResource(media));
```
or this:
```java
AudioInputStream input = AudioSystem.getAudioInputStream(new BufferedInputStream(Resources.class.getResourceAsStream(media)));
```
